export default {
    SIGN_IN: 'SIGN_IN',
    SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_IN_WARNING:'SIGN_IN_WARNING',
    SIGN_OUT: 'SIGN_OUT',
    
    SIGN_UP: 'SIGN_UP',
    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    UPDATE_ACCOUNT_PASSWORD: 'UPDATE_ACCOUNT_PASSWORD'

}