export default [
    {
        id:1,
        name:"User",
        backgroundColor:"orange",
        color:"white"
    },
    {
        id:2,
        name:"Customer",
        backgroundColor:"yellow",
        color:"black"
    },
    {
        id:3,
        name:"Product",
        backgroundColor:"blue",
        color:"white"
    },
    {
        id:4,
        name:"FeedbackFAQ",
        backgroundColor:"red",
        color:"white"
    },
    {
        id:5,
        name:"Orders",
        backgroundColor:"blue",
        color:"white"
    },
    {
        id:6,
        name:"Profile",
        backgroundColor:"orange",
        color:"white"
    },
    {
        id:7,
        name:"Change Pass",
        backgroundColor:"green",
        color:"white"
    },
    {
        id:8,
        name:"Logout",
        backgroundColor:"red",
        color:"white"
    }
]